backend:
  name: github
  repo: stuut/morethanmulch

media_folder: static/
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - {  label: Date, name: date,widget: date }
      - {  label: Title, name: title,}
      - {  label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list}
      - { label: author, name: author, }
      - { label: category, name: category, }
      - { label: mainImage, name: mainImage, widget: image}
