backend:
  name: github
  repo: stuut/netlify-cms-tutorial

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {label: "Tags", name: "tags", widget: "list"}
